pipeline {
    
    agent any

    stages {
        stage('Terraform Init') {
            steps {
                sh 'terraform init'
            }
        }
        stage('Terraform Plan') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'terraform-creds', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
                    sh "export TF_VAR_username=$USERNAME"
                    sh "export TF_VAR_password=$PASSWORD"
                    sh 'terraform plan'
                }
            }
        }
        stage('Terraform Apply') {
            steps {
                sh 'echo mock terraform apply' 
                //sh 'terraform apply -auto-approve'
            }
        }
    }
}